### ISSUE TITLE
Docker - config.json is ignored

### ISSUE THREAD

**Issue by daedric7** [ajbura/cinny#1314]
### Describe the bug

I'm using Cinny with docker (via docker compose).

config.json is mounted inside the container in /app/config.json.

Yet, aparently it's being ignored, the defaults always show up.

### Reproduction

**docker-compose.yaml:**

```
version: '3.3'
services:
    cinny:
        image: 'ghcr.io/cinnyapp/cinny:latest'
        restart: always
        volumes:
            - ./config.json:/app/config.json
```

**config.json:**

```
{
  "defaultHomeserver": 0,
  "homeserverList": [
    "myserver.com"
  ],
  "allowCustomHomeservers": false
}
```

### Expected behavior

Only one server available on the server selection ,without option to use custom server.

### Platform and versions

```shell
Oracle Free Arm, official docker.
```
