### ISSUE TITLE
[feat] Multi platform docker image

### ISSUE THREAD

**Issue by SaltireSoul** [ajbura/cinny#489]
### Describe the problem

Docker image is only available for amd64

### Describe the solution you'd like

Use existing github action to build and push multi platform images.
add platforms to prod-deploy.yml

for example:
```
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
